### PR TITLE
Minor update to HTML/CSS

### PR DESCRIPTION
**Pull request by Rachella**

### CODE REVIEW

**Comment by h8rry** [comment]
"This branch has conflicts that must be resolved". Can you try rebasing and solve all conflicts?

**Comment by Rachella** [comment]
Would that cause an issue to the second PR I sent? Branch "Patch" is based off of "HTML"...

**Comment by h8rry** [comment]
Possibly, but the `patch` branch seems fine

**Comment by Rachella** [comment]
conflicts resolved - it was minor _phew_

**Comment by h8rry** [comment]
Looks good

**Pull request merged**
